# Generated by Django 5.2 on 2025-04-28 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('amount', models.IntegerField(default=1)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=64)),
                ('fullname', models.CharField(max_length=256)),
                ('school_name', models.CharField(max_length=256)),
                ('town', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('allow_personal', models.BooleanField(default=True)),
                ('promo_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teachers.promo')),
            ],
        ),
    ]
